export const GET_INGREDIENTS = 'GET_INGREDIENTS';

export const GET_BURGER_INGREDIENTS = 'GET_BURGER_INGREDIENTS';

export const ADD_INGREDIENT_DETAILS = 'ADD_INGREDIENT_DETAILS';
export const DELETE_INGREDIENT_DETAILS = 'DELETE_INGREDIENT_DETAILS'